= Hypospray proxy design
:doctype: article
:author: Jan Beernink

Design for proxy classes generated by Hypospray.

Hypospray will rely on generated proxy classes that will be used to proxy beans and other classes. To allow flexibility, the core of the proxy will be invokers.

== Proxy class name

The Hypospray proxy classes will be placed in the same package as the class that is being proxied, whenever possible. The class name of the generated proxy class will follow the format `proxiedClassName\$$hypospray$proxy`. So for a class named `eu.jbeernink.foo.Bar`, the proxy class will be named `eu.jbeernink.foo.Bar$$hypospray$proxy`.

=== Bean producer proxy class name

TODO: define the class name for the return type of a bean producer proxy.

== Constructor

Hypospray generated proxy classes will have a simple constructor that takes a single argument. This argument will be a function that can be used to perform a lookup to obtain an Invoker instance based on a method identifier.

The use of Invokers will allow much more flexibility in the implementation of the proxy. If the proxy is for a scoped bean, the provided Invoker lookup function can perform a lookup to return an invoker that resolves the bean at invocation time.

== Invoker lookup function

The invoker lookup function will of the type `java.util.function.Function<String, Invoker<Void, ?>>`. For the proxy implementation, the actual implementation of this function is not important. The invoker that will be returned will only accept `null` as the instance parameter, and will return the actual result of the method. The proxy method will ensure that the returned value will be cast to the correct type.

== Method identifier

In order to the proxy to lookup an invoker for a method, a method identifier is required. This method identifier should not rely upon an reflective types, as they may or may not be available at runtime, and must only use types that are available in the `java.base` module. To this end, the method identifier will take the form of a string.

Please see the <<Method Identifier>> section for more details on the format of method identifiers.

== Proxy methods

The proxied methods will be simple and first perform a lookup for the invoker and then pass all arguments to it. The instance argument to the invoker will always be `null`, the invoker itself will be responsible for obtaining the instance of the proxied bean.

How exceptions are handled depends on if any exceptions are declared in the throws clause of the method. The proxy method should directly rethrow any RuntimeException or exception defined in the proxied method's throw clause. As the invoker will throw `java.lang.Exception` by default, any other exceptions should be caught and wrapped in a `java.lang.reflect.InvocationTargetException`. However, in normal circumstances this should not happen.

As an example, let's take a proxy method for `Object.equals()`. If written as Java source code, the proxy method would look like something along the following lines:

[source,java]
----
@Override
public boolean equals(Object other) {
  Invoker<Void, Object> invoker = invokerFactory.get("equals[(Ljava.lang.Object;)Z]");
  return (boolean) invoker.invoke(null, new Object[]{other});
}
----

== Full example

As an example, let's take the following class:
[source, java]
----
include::{baseDir}/src/main/java/eu/jbeernink/hypospray/docs/proxy/ProxiedClass.java[]
----

The proxy for the above would look like the following when written as Java source code:

[source, java]
----
include::{baseDir}/src/main/java/eu/jbeernink/hypospray/docs/proxy/ProxiedClass$$hypospray$proxy.java[]
----
