<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>eu.jbeernink.hypospray</groupId>
		<artifactId>codegeneration</artifactId>
		<version>${revision}</version>
	</parent>

	<groupId>eu.jbeernink.hypospray.codegeneration</groupId>
	<artifactId>eu.jbeernink.hypospray.codegeneration.classfile</artifactId>
	<version>${revision}</version>

	<dependencies>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray</groupId>
			<artifactId>eu.jbeernink.hypospray.annotation</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.codegeneration</groupId>
			<artifactId>eu.jbeernink.hypospray.codegeneration.generator</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.codegeneration</groupId>
			<artifactId>testing</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- TODO: Temporary dependency for testing, please remove. -->
		<dependency>
			<groupId>eu.jbeernink.hypospray.testing</groupId>
			<artifactId>openmodule</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.compile</groupId>
			<artifactId>eu.jbeernink.hypospray.compile.servicedescriptor</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>eu.jbeernink.hypospray.compile</groupId>
							<artifactId>eu.jbeernink.hypospray.compile.servicedescriptor</artifactId>
							<version>${project.version}</version>
						</path>
					</annotationProcessorPaths>
					<annotationProcessors>
						<annotationProcessor>eu.jbeernink.hypospray.compile.servicedescriptor.ServiceDescriptorGenerator
						</annotationProcessor>
					</annotationProcessors>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>